// Exported from Plass
#set page(paper: "us-letter", margin: 1.25in, numbering: "1", number-align: center)
#set par(justify: true, leading: 10.215pt, spacing: 21.465pt)
#set list(spacing: 13.340pt)
#set enum(spacing: 13.340pt)
#show heading.where(level: 1): set text(size: 23.750pt)
#show heading.where(level: 1): set block(above: 26.391pt, below: 25.105pt)
#show heading.where(level: 1): set par(leading: 13.471pt)
#show heading.where(level: 2): set text(size: 17.500pt)
#show heading.where(level: 2): set block(above: 44.650pt, below: 19.937pt)
#show heading.where(level: 2): set par(leading: 9.926pt)
#show heading.where(level: 3): set text(size: 14.375pt)
#show heading.where(level: 3): set block(above: 38.410pt, below: 18.473pt)
#show heading.where(level: 3): set par(leading: 8.153pt)
#show raw.where(block: false): set text(font: "DejaVu Sans Mono", size: 10.000pt)
#show math.equation.where(block: true): set block(above: 21.490pt, below: 23.702pt)
#set text(size: 12.5pt, font: "New Computer Modern", hyphenate: true)
#set math.equation(numbering: "(1)")

Elasticity visualization: use a horizontal line composed of two parts, the change part and the base part. This could show the idea that elasticity is a way of measuring the responsiveness and not just the slope. I'm thinking about a visual like grant's bayes video. The elasticity measure could be slighly different than the midpoint method, using the smaller of the two values instead of the middle of the two values. Then visualize the horizontal axis with a horizontal line in the elasticty fraction and the vertical in the elasticity fraction. Then have both up and down different colors and the changes part be a more vibrant color and the base be a muted color. Then move the base around moving the lines in the fraction. Then fade in the numbers, adding the number beside the bars in the SD graph and in the elasticity equation. Then show the elasticity number itself by the fraction. Then move it around. Then color the regions where it's elastic, and inelastic and fade in a bracket labeling each region.
