## https://docs.manim.community/en/v0.10.0/reference.html

# Model geometry shared across episodes (PPFs, supply, cost, consumer helpers).
# Import from an episode after adding _Assets to sys.path:  from Video import *
import os
import warnings
from manim import *

""" Intro Sequence """

# https://render.fontstruct.com/renderer/render?id=261025&v=5afd1b5b&w=800&h=400&sz=100&wr=1&pds=all
# Blues, Reds, Greys, Purples, Greens, Oranges
# https://medium.com/@morganjonesartist/color-guide-to-seaborn-palettes-da849406d44f
# Paired, Spectral, Pastel1,  
# PuBu, PuBuGn, CMRmap, GnBu, OrRd, PRGn, PiYG, PuOr, PuRd, RdBu, RdGy, RdPu, RdYlBu, RdYlGn, YlGn, YlGnBu, YlOrBr



""" Part A Definitions """

# Canonical Part A numbers (settled 2026-08-24): Molly 10 carrots / 40 spinach,
# Andrew 8 carrots / 16 spinach. Axes: carrots HORIZONTAL, spinach VERTICAL, so
# each PPF plots as S(C) and the slope is the opportunity cost of a carrot.
# PPF_Coop is the co-op's no-specialization line through the summed extremes
# (18 C, 56 S); the equal-ratio split (9, 28) sits on it, and the
# specialization point (8, 40) is the kink of the true joint frontier.
# (Updated with the A2 sweep, 2026-08-30. A3's old scene code still assumes
# the pre-flip spinach-first functions and gets rewritten in the A3 port.)

def PPF_Function(c):
    return 40 - 4*c

def PPF_Function_New(c):
    alpha = 4/5
    return 40*alpha - 4*c

def PPF_Function_Tech(c):
    alpha = 4/5
    return 40*alpha - 2*c

PPF_Molly = PPF_Function     # A1's function of record, under its Part-A name

def PPF_Andrew(c):
    return 16 - 2*c

def PPF_Coop(c):
    return 56 - 28*c/9

""" Part B Definitions """

def Supply_Curve(q):
    return q/250

def New_Supply_Curve(q):
    return q/250 + 2
    
def Molly_Supply(q):
    return q/250

def Andrew_Supply(q):
    return q/100

def Andrew_Supply_Inv(p):
    return 100*p

def Supply(q):
    return q/350

""" Part D Definitions """

def Production_Function(L):
    """ Standard Cobb-Douglass """
    
    return L**(1/2)

def Inv_F(Q):
    """ Inverse Cobb_Douglass """
    
    return Q**2

w = 2

def VC(Q):
    """ From Cobb-Douglass """
    
    return Q**2 * w

def FC(Q):
    """ Constant """
    
    return 80

def TC(Q):
    
    return VC(Q) + FC(Q)

def AVC(Q):
    
    return VC(Q) / Q

def ATC(Q):
    
    return TC(Q) / Q

def AFC(Q):
    
    return FC(Q) / Q

def MC(Q):
    
    return 2 * w * Q 
    
""" Format Videos """

def Make_MOV(video_path, episode_name=None):
    """ Concat mp4 files. """
    media_dir = getattr(config, 'media_dir', 'media')
    if episode_name is None:
        episode_name = media_dir

    video_names = os.listdir(video_path)
    video_names = sorted([x for x in video_names if x.split('.')[-1] == 'mp4'])
    video_paths = ["file '" + video_path + x + "'" for x in video_names]
    text = '\n'.join(video_paths)

    with open('concat.txt', 'w') as f:
        f.write(text)

    output_name = os.path.join(video_path, episode_name + '.mp4')
    os.system('ffmpeg -f concat -safe 0 -i concat.txt -c copy ' + output_name + ' -y')

    os.system('rm concat.txt')
    
    
    """ Convert the mp4 files generated by manim to mov. """
    
    video_names = os.listdir(video_path)
    video_names = [x for x in video_names if '.mp4' in x]

    for video_name in video_names:
        open_path = video_path + video_name
        options = ' -vcodec  mjpeg -q:v 2 -acodec pcm_s16be -q:a 0 -f mov '
        close_path = video_path + video_name.replace('.mp4','_convert.mov')
        
        os.system('ffmpeg -i ' + open_path + options + close_path + ' -y')
        
    """ Copy converted concated file. """
    
    output_name = os.path.join(video_path, episode_name + '.mp4')
    video_name = os.path.join(media_dir, episode_name + '.mp4')
    os.system('cp '+ output_name + ' ' + video_name)
    
    os.system('rm '+output_name)
    os.system('rm '+output_name.replace('.mp4','.mov'))


""" General Definitions """


def circle_it(self, radius, point):
    circle_1 = Circle(radius).move_to(point)
    a = Dot(radius = 0.01, color=YELLOW)
    b = TracedPath(a.get_center, dissipating_time=0.3, stroke_opacity=[0, 1]).set_color(YELLOW)
    self.add(a, b)
    self.play(MoveAlongPath(a, circle_1), run_time=1/2)
    self.play(FadeOut(a), FadeOut(b), run_time=1/4)

    
def box_it(self, radius, point):
    framebox = SurroundingRectangle(point, buff = 0.3)
    a = Dot(radius = 0.01, color=YELLOW, z_index=22)
    b = TracedPath(a.get_center, dissipating_time=0.3, stroke_opacity=[0, 1], z_index=22).set_color(YELLOW)
    self.add(a, b)
    self.play(MoveAlongPath(a, framebox), run_time=1/2)
    self.play(FadeOut(a), FadeOut(b), run_time=1/4)
    

def framebox_it(self, item, t=1/2):
    framebox = SurroundingRectangle(item, buff = 0.3, z_index=11).set_color(BLUE)
    self.play(Create(framebox), runtime=t)
    framebox.flip(RIGHT)
    self.play(Uncreate(framebox), runtime=t)


""" Part C | Animation 1 and 2 """

def consumer_graph():
    axes = Axes(
        x_range=[0, 100, 100],
        x_length = 5,
        x_axis_config={
            "numbers_to_include": [80],
            "decimal_number_config": {"num_decimal_places":0, 'color':BLUE},
        },
        y_range=[0, 100, 100],
        y_length = 5,
        y_axis_config={
            "numbers_to_include": [80],
            "decimal_number_config": {"num_decimal_places":0, 'color':GREEN}
        },
        tips=False,
    )
    x_label = axes.get_x_axis_label("A").set_color(BLUE)
    y_label = axes.get_y_axis_label("B").set_color(GREEN)
    
    return axes, VGroup(x_label, y_label)


def engle_graph():
    engle = Axes(
        x_range=[0, 100, 100],
        x_length = 5,
        x_axis_config={
            "numbers_to_include": [80],
            "decimal_number_config": {"num_decimal_places":0, 'color':BLUE},
        },
        y_range=[0, 150, 150],
        y_length = 5,
        y_axis_config={
            "numbers_to_include": [],
            "decimal_number_config": {"num_decimal_places":0, 'color':RED}
        },
        tips=False,
    )
    y_label = engle.get_y_axis_label("Y").set_color(RED)
    x_label = engle.get_x_axis_label("A").set_color(BLUE)
    return engle, VGroup(x_label, y_label)


def demand_graph():
    engle = Axes(
        x_range=[0, 100, 100],
        x_length = 5,
        x_axis_config={
            "numbers_to_include": [80],
            "decimal_number_config": {"num_decimal_places":0, 'color':BLUE},
        },
        y_range=[0, 7, 7],
        y_length = 5,
        y_axis_config={
            "numbers_to_include": [6],
            "decimal_number_config": {"num_decimal_places":0, 'color':BLUE}
        },
        tips=False,
    )
    y_label = engle.get_y_axis_label("P_A")
    x_label = engle.get_x_axis_label("A").set_color(BLUE)
    return engle, VGroup(x_label, y_label)


""" Budget Constraint """


def budget_constraint(a, Y, price_a, price_b):
    """ Use the equation for the budget line to return the quantity of b. """
    
    return (Y - price_a * a) / price_b


def move_budget_constraint(axes, Y, price_a, price_b):
    """ Return a plot of the budget line. """
    
    x_max = min(100, Y.get_value()/price_a.get_value())
    return axes.plot(lambda a: budget_constraint(a, Y, price_a, price_b), color=RED, x_range=(0, x_max))


def move_budget_dot(axes, quantity_a, Y, price_a, price_b):
    """ Move a dot along the budget line, with intersection lines. """
    
    x = quantity_a.get_value()
    x_int = axes.coords_to_point(x,0)
    x_label = DecimalNumber(num_decimal_places=2).next_to(x_int,DOWN).set_value(x).set_color(BLUE)
    
    y = budget_constraint(x, Y, price_a, price_b)
    y_int = axes.coords_to_point(0,y)
    y_label = DecimalNumber(num_decimal_places=2).next_to(y_int,LEFT).set_value(y).set_color(GREEN)
    
    p = axes.coords_to_point(x,y)
    dot = Dot(p, z_index=10).set_color(YELLOW)
    
    vline = DashedLine(x_int,p).set_color(GREY)
    hline = DashedLine(y_int,p).set_color(GREY)
    
    return VGroup(dot,vline,hline,x_label,y_label)


""" Indifference Curve """


def utility(quantity_a, quantity_b, tracker=True):
    if tracker:
        return (quantity_a.get_value() * quantity_b.get_value())**(1/2)
    else:
        return (quantity_a * quantity_b)**(1/2)
    

def indifference_curve(U, a, tracker=True):
    if tracker:
        return U.get_value()**2 / a
    else:
        return U**2 / a


def move_indifference_dot(axes, quantity_a, U):
    """ Move a dot along the indifference curve, with intersection lines. """
    
    x = quantity_a.get_value()
    x_int = axes.coords_to_point(x,0)
    x_label = DecimalNumber(num_decimal_places=2).next_to(x_int,DOWN).set_value(x).set_color(BLUE)
    
    y = indifference_curve(U, x)
    y_int = axes.coords_to_point(0,y)
    y_label = DecimalNumber(num_decimal_places=2).next_to(y_int,LEFT).set_value(y).set_color(GREEN)
    
    p = axes.coords_to_point(x,y)
    dot = Dot(p, z_index=10).set_color(YELLOW)
    
    vline = DashedLine(x_int,p).set_color(GREY)
    hline = DashedLine(y_int,p).set_color(GREY)
    
    return VGroup(dot,vline,hline,x_label,y_label)


def move_indifference_curve(axes, U, tracker=True):
    """ Move the MRS line along the indifference curve. """
    
    x_min = min([a for a in np.arange(0, 100, 0.1) if indifference_curve(U, a) < 100])
    
    if tracker:
        return axes.plot(lambda a: indifference_curve(U, a), color=YELLOW, x_range=(x_min, 100, 0.1))
    else:
        return axes.plot(lambda a: indifference_curve(U, a, tracker=False), color=YELLOW, x_range=(x_min, 100, 0.1))
    

def move_indifference_label(axes, U, p):
    label = VGroup(
        Text("U = ").scale(0.8),
        DecimalNumber(num_decimal_places=1).set_value(U.get_value())
    ).set_color(YELLOW)
    
    return label.arrange(RIGHT).next_to(p, RIGHT*2+UP*2)


def mrs_line(quantity_a, U, a):
    """ Use the equation for the MRS line to return the quantity of b. """
    
    quantity_a = quantity_a.get_value()
    derivative = - U.get_value()**2 / quantity_a**2
    quantity_b = indifference_curve(U, quantity_a)
    b_intercept = quantity_b - derivative*quantity_a
    
    return b_intercept + derivative*a


def move_mrs_line(axes, quantity_a, U):
    """ Move the MRS line along the indifference curve. """
    
    return axes.plot(lambda a: mrs_line(quantity_a, U, a), color=PURPLE, x_range=(0, 100, 1), z_index=-10)


""" Consumer Problem """


def solution_a(Y, price_a):
    """ The solution to the consumer's problem for a. """
    
    return Y.get_value() / (2 * price_a.get_value())


def solution_b(Y, price_b):
    """ The solution to the consumer's problem for b. """
    
    return Y.get_value() / (2 * price_b.get_value())


def consumer_solution(axes, Y, price_a, price_b):
    """ Graph the consumer solution. """
    
    a = solution_a(Y, price_a)
    b = solution_b(Y, price_b)
    u = utility(a, b)
    p = axes.coords_to_point(a,b)
    dot = Dot(p, z_index=10).set_color(YELLOW)

    budget = move_budget_constraint(axes, Y, price_a, price_b, tracker=True)
    indifference = move_Indifference_curve(axes, u)
    label = move_Indifference_label(axes, u, p)
    
    return dot, budget, indifference, label


def consumer_solution_dot(axes, Y, price_a, price_b):
    """  """
    
    quantity_a = solution_a(Y, price_a)
    quantity_b = solution_b(Y, price_b)
    p = axes.coords_to_point(quantity_a,quantity_b)
    dot = Dot(p, z_index=10).set_color(YELLOW)
    
    a_int = axes.coords_to_point(quantity_a,0)
    a_label = DecimalNumber(num_decimal_places=1).next_to(a_int, DOWN*2).set_value(quantity_a).set_color(BLUE)
    
    b_int = axes.coords_to_point(0,quantity_b)
    b_label = DecimalNumber(num_decimal_places=1).next_to(b_int, LEFT*2).set_value(quantity_b).set_color(GREEN)
    
    vline = DashedLine(a_int,p).set_color(GREY)
    hline = DashedLine(b_int,p).set_color(GREY)
    
    return VGroup(dot, vline, hline, a_label, b_label)
    

def consumer_solution_indifference(axes, Y, price_a, price_b):
    
    quantity_a = solution_a(Y, price_a)
    quantity_b = solution_b(Y, price_b)
    U = utility(quantity_a, quantity_b, tracker=False)
    
    return move_indifference_curve(axes, U, tracker=False)


def consumer_solution_label(axes, Y, price_a, price_b):
    
    quantity_a = solution_a(Y, price_a)
    quantity_b = solution_b(Y, price_b)
    p = axes.coords_to_point(quantity_a,quantity_b)
    U = utility(quantity_a, quantity_b, tracker=False)
    
    label = VGroup(
        Text("U = ").scale(0.8),
        DecimalNumber(num_decimal_places=1).set_value(U)
    ).set_color(YELLOW)
    
    return label.arrange(RIGHT).next_to(p, RIGHT*2+UP*2)


""" Engle Curve """

def plot_engle_a(axes, Y, price_a, price_b):
    """ Plot a point on the engle curve. """
    
    a = solution_a(Y, price_a)
    a_int = axes.coords_to_point(a,0)
    a_label = DecimalNumber(num_decimal_places=1).next_to(a_int,DOWN*2).set_value(a).set_color(BLUE)

    y = Y.get_value()
    y_int = axes.coords_to_point(0,y)
    y_label = DecimalNumber(num_decimal_places=1).next_to(y_int,LEFT*2).set_value(y).set_color(RED)

    p = axes.coords_to_point(a,y)
    dot = Dot(p, z_index=11).set_color(YELLOW)

    vline = DashedLine(a_int,p).set_color(GREY)
    hline = DashedLine(y_int,p).set_color(GREY)

    return VGroup(dot, a_label, y_label, vline, hline)


""" Individual Demand """


def plot_demand_a(axes, Y, price_a):
    """ Plot a point on the individual demand curve. """
    
    a = solution_a(Y, price_a)
    a_int = axes.coords_to_point(a,0)
    a_label = DecimalNumber(num_decimal_places=1).next_to(a_int,DOWN*2).set_value(a).set_color(BLUE)

    price = price_a.get_value()
    price_int = axes.coords_to_point(0,price)
    price_label = DecimalNumber(num_decimal_places=1).next_to(price_int,LEFT*2).set_value(price).set_color(BLUE)

    p = axes.coords_to_point(a,price)
    dot = Dot(p, z_index=11).set_color(YELLOW)

    vline = DashedLine(a_int,p).set_color(GREY)
    hline = DashedLine(price_int,p).set_color(GREY)

    return VGroup(dot, a_label, price_label, vline, hline)